<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Output\IOutputPort.fs" />
    <Compile Include="DiploConfig.fs" />
    <Compile Include="ImageCatalog.fs" />
    <Compile Include="Mounts\MountParser.fs" />
    <Compile Include="CommandLine.fs" />
    <Compile Include="Connection\GrpcClientFactory.fs" />
    <Compile Include="Connection\DiploChannel.fs" />
    <Compile Include="Clients\GrpcClientBase.fs" />
    <Compile Include="Clients\ClientInterfaces.fs" />
    <Compile Include="Clients\ContainerClient.fs" />
    <Compile Include="Clients\VolumeClient.fs" />
    <Compile Include="Clients\NetworkClient.fs" />
    <Compile Include="Clients\DiploClients.fs" />
    <Compile Include="Compose\ComposeModels.fs" />
    <Compile Include="Compose\ComposeOrchestrator.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="protobuf-net.Grpc" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Diplo.Grpc\Diplo.Grpc.fsproj" />
    <ProjectReference Include="..\Diplo.Abstractions\Diplo.Abstractions.fsproj" />
  </ItemGroup>

</Project>
