<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <EnableDefaultProtobufItems>false</EnableDefaultProtobufItems>
    <Protobuf_ProjectSupported>true</Protobuf_ProjectSupported>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Plugins\INetworkDriver.fs" />
    <Compile Include="Plugins\CniParsing.fs" />
    <Compile Include="Plugins\BridgeDriver.fs" />
    <Compile Include="Plugins\CustomCniDriver.fs" />
    <Compile Include="Plugins\NoneDriver.fs" />
    <Compile Include="Plugins\PodDriver.fs" />
    <Compile Include="Services\NetworkServiceImpl.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Diplo.Contracts\Diplo.Contracts.fsproj" />
    <ProjectReference Include="..\Diplo.Abstractions\Diplo.Abstractions.fsproj" />
    <ProjectReference Include="..\Diplo.Grpc\Diplo.Grpc.csproj" />
  </ItemGroup>
</Project>
