<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>

  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Drivers\RemoteVolumeStore.fs" />
    <Compile Include="Drivers\VolumeDriverRegistry.fs" />
    <Compile Include="Drivers\LocalDriver.fs" />
    <Compile Include="Drivers\RemoteDriverBase.fs" />
    <Compile Include="Drivers\NfsDriver.fs" />
    <Compile Include="Drivers\SmbDriver.fs" />
    <Compile Include="Drivers\CloudAzureDriver.fs" />
    <Compile Include="Drivers\CloudAwsDriver.fs" />
    <Compile Include="Drivers\CloudGcpDriver.fs" />
    <Compile Include="Drivers\IsoDriver.fs" />
    <Compile Include="Services\VolumeServiceImpl.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net.Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Core.Api" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Diplo.Contracts\Diplo.Contracts.fsproj" />
    <ProjectReference Include="..\Diplo.Abstractions\Diplo.Abstractions.fsproj" />
    <ProjectReference Include="..\Diplo.Grpc\Diplo.Grpc.fsproj" />
    <ProjectReference Include="..\Diplo.Disk\Diplo.Disk.fsproj" />
  </ItemGroup>
</Project>
