<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DiskFormat.fs" />
    <Compile Include="Qcow2.fs" />
    <Compile Include="FsImage.fs" />
    <Compile Include="DiskMounter.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LTRData.DiscUtils" />
  </ItemGroup>

</Project>
