<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="VolumeIntegrationTests.fs" />
    <Compile Include="ContainerIntegrationTests.fs" />
    <Compile Include="NetworkIntegrationTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="FsUnit.xUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Diplo.Grpc\Diplo.Grpc.fsproj" />
    <ProjectReference Include="..\..\src\Diplo.Abstractions\Diplo.Abstractions.fsproj" />
    <ProjectReference Include="..\..\src\Diplo.Volume\Diplo.Volume.fsproj" />
    <ProjectReference Include="..\..\src\Diplo.Container\Diplo.Container.fsproj" />
    <ProjectReference Include="..\..\src\Diplo.Network\Diplo.Network.fsproj" />
  </ItemGroup>

</Project>
