<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="LocalDriverTests.fs" />
    <Compile Include="RemoteVolumeStoreTests.fs" />
    <Compile Include="IsoDriverTests.fs" />
    <Compile Include="MockVolumeDriver.fs" />
    <Compile Include="VolumeServiceImplTests.fs" />
    <Compile Include="RemoteDriverHelpersTests.fs" />
    <Compile Include="RemoteDriverTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"  />
    <PackageReference Include="FSharp.Core"  />
    <PackageReference Include="xunit.v3"  />
    <PackageReference Include="xunit.runner.visualstudio" >
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FsUnit.xUnit"  />
    <PackageReference Include="Grpc.Core.Testing"  />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Diplo.Abstractions\Diplo.Abstractions.fsproj" />
    <ProjectReference Include="..\..\src\Diplo.Volume\Diplo.Volume.fsproj" />
    <ProjectReference Include="..\..\src\Diplo.Grpc\Diplo.Grpc.fsproj" />
  </ItemGroup>

</Project>
