<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>

  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Clients\ProcessRunner.fs" />
    <Compile Include="Clients\ContainerdClient.fs" />
    <Compile Include="Services\ContainerServiceImpl.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net.Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Core.Api" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Diplo.Contracts\Diplo.Contracts.fsproj" />
    <ProjectReference Include="..\Diplo.Abstractions\Diplo.Abstractions.fsproj" />
    <ProjectReference Include="..\Diplo.Grpc\Diplo.Grpc.fsproj" />
  </ItemGroup>
</Project>
