<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Diplo.Linux</RootNamespace>
    <Description>Émulateur de machine Linux sur Windows (traduction de syscalls, style WSL1)</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Registers.fs" />
    <Compile Include="Memory.fs" />
    <Compile Include="ElfLoader.fs" />
    <Compile Include="Decoder.fs" />
    <Compile Include="Syscalls.fs" />
    <Compile Include="Emulator.fs" />
    <Compile Include="LinuxMachine.fs" />
    <Compile Include="BootImage.fs" />
    <Compile Include="KernelImage.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ZstdSharp.Port" />
  </ItemGroup>

</Project>
