<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DiploChannelTests.fs" />
    <Compile Include="ContainerClientTests.fs" />
    <Compile Include="VolumeClientTests.fs" />
    <Compile Include="NetworkClientTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FsUnit.xUnit" Version="7.1.1" />
    <PackageReference Include="Grpc.Core.Testing" Version="2.46.6" />
    <PackageReference Include="Grpc.Net.Client" Version="2.80.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Diplo.Abstractions\Diplo.Abstractions.fsproj" />
    <ProjectReference Include="..\..\src\Diplo.Core\Diplo.Core.fsproj" />
    <ProjectReference Include="..\..\src\Diplo.Grpc\Diplo.Grpc.csproj" />
  </ItemGroup>

</Project>
