<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Diplo.Installer</RootNamespace>
    <AssemblyName>Diplo.Installer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ArtifactSigning.fs" />
    <Compile Include="Core.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\artifacts.manifest" LogicalName="Diplo.Installer.assets.artifacts.manifest" />
    <EmbeddedResource Include="assets\artifacts.manifest.sig" LogicalName="Diplo.Installer.assets.artifacts.manifest.sig" />
    <EmbeddedResource Include="assets\diplo-release.pub" LogicalName="Diplo.Installer.assets.diplo-release.pub" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Diplo.Abstractions\Diplo.Abstractions.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController"  />
    <PackageReference Include="FSharp.Core"  />
  </ItemGroup>

</Project>
