<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AppSettingsJsonTests.fs" />
    <Compile Include="ArtifactSigningTests.fs" />
    <Compile Include="CoreTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"  />
    <PackageReference Include="FSharp.Core"  />
    <PackageReference Include="xunit.v3"  />
    <PackageReference Include="FsUnit.xUnit"  />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DiploWalker.Installer\DiploWalker.Installer.fsproj" />
  </ItemGroup>

</Project>

