<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ViewModels\ViewModelBase.fs" />
    <Compile Include="Services\AvaloniaOutputPort.fs" />
    <Compile Include="ViewModels\MainWindowViewModel.fs" />
    <AvaloniaResource Include="Views\MainWindow.axaml" />
    <Compile Include="Views\MainWindow.axaml.fs" />
    <AvaloniaResource Include="App.axaml" />
    <Compile Include="App.axaml.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia"  />
    <PackageReference Include="Avalonia.Desktop"  />
    <PackageReference Include="Avalonia.Themes.Fluent"  />
    <PackageReference Include="Avalonia.Controls.DataGrid"  />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Diplo.Core\Diplo.Core.fsproj" />
  </ItemGroup>

</Project>
