<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="MockContainerdClient.fs" />
    <Compile Include="MockProcessRunner.fs" />
    <Compile Include="ContainerdClientTests.fs" />
    <Compile Include="ContainerServiceImplTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"  />
    <PackageReference Include="xunit.v3"  />
    <PackageReference Include="xunit.runner.visualstudio" >
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FsUnit.xUnit"  />
    <PackageReference Include="Grpc.Core.Testing"  />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Diplo.Abstractions\Diplo.Abstractions.fsproj" />
    <ProjectReference Include="..\..\src\Diplo.Container\Diplo.Container.fsproj" />
    <ProjectReference Include="..\..\src\Diplo.Grpc\Diplo.Grpc.fsproj" />
  </ItemGroup>

</Project>
