<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>Diplo.Linux.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ElfTest.fs" />
    <Compile Include="LinuxMachineTests.fs" />
    <Compile Include="VirtualMemoryTests.fs" />
    <Compile Include="BootTests.fs" />
    <Compile Include="BootIsoTests.fs" />
    <Compile Include="KernelImageTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="FsUnit.xUnit" />
    <PackageReference Include="ZstdSharp.Port" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Diplo.Linux\Diplo.Linux.fsproj" />
    <ProjectReference Include="..\..\src\Diplo.Volume\Diplo.Volume.fsproj" />
  </ItemGroup>

</Project>
